[Waveshare_S3_LR1121_XF]
extends = esp32_base
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qspi
board_build.partitions = default.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
build_flags =
  ${esp32_base.build_flags}
  -I variants/waveshare-s3-lr1121-xf
  -D WAVESHARE_S3_LR1121_XF
  -D P_LORA_NSS=42
  -D P_LORA_SCLK=40
  -D P_LORA_MOSI=45
  -D P_LORA_MISO=46
  -D P_LORA_RESET=39
  -D P_LORA_BUSY=41
  -D P_LORA_DIO_1=38
  -D RADIO_CLASS=WaveshareS3LR1121XF
  -D WRAPPER_CLASS=CustomLR1121Wrapper
  -D LORA_TX_POWER=22
  -D RF_SWITCH_TABLE
  -D RX_BOOSTED_GAIN=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/waveshare-s3-lr1121-xf>
lib_deps =
  ${esp32_base.lib_deps}
  ${esp32_ota.lib_deps}

[env:Waveshare_S3_LR1121_XF_repeater]
extends = Waveshare_S3_LR1121_XF
build_flags =
  ${Waveshare_S3_LR1121_XF.build_flags}
  -D ADVERT_NAME='"Waveshare S3 LR1121 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
build_src_filter = ${Waveshare_S3_LR1121_XF.build_src_filter}
  +<../examples/simple_repeater>

[env:Waveshare_S3_LR1121_XF_repeater_bridge_espnow]
extends = Waveshare_S3_LR1121_XF
build_flags =
  ${Waveshare_S3_LR1121_XF.build_flags}
  -D ADVERT_NAME='"ESPNow Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D WITH_ESPNOW_BRIDGE=1
build_src_filter = ${Waveshare_S3_LR1121_XF.build_src_filter}
  +<helpers/bridges/ESPNowBridge.cpp>
  +<../examples/simple_repeater>
lib_deps =
  ${Waveshare_S3_LR1121_XF.lib_deps}
  ${esp32_ota.lib_deps}

[env:Waveshare_S3_LR1121_XF_repeater_bridge_rs232_serial0]
extends = Waveshare_S3_LR1121_XF
build_flags =
  ${Waveshare_S3_LR1121_XF.build_flags}
  -D ADVERT_NAME='"RS232 Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D WITH_RS232_BRIDGE=bridge_serial
  -D WITH_RS232_BRIDGE_RX=44
  -D WITH_RS232_BRIDGE_TX=43
build_src_filter = ${Waveshare_S3_LR1121_XF.build_src_filter}
  +<helpers/bridges/RS232Bridge.cpp>
  +<../examples/simple_repeater>
lib_deps =
  ${Waveshare_S3_LR1121_XF.lib_deps}
  ${esp32_ota.lib_deps}

[env:Waveshare_S3_LR1121_XF_terminal_chat]
extends = Waveshare_S3_LR1121_XF
build_flags =
  ${Waveshare_S3_LR1121_XF.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=1
build_src_filter = ${Waveshare_S3_LR1121_XF.build_src_filter}
  +<../examples/simple_secure_chat/main.cpp>
lib_deps =
  ${Waveshare_S3_LR1121_XF.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Waveshare_S3_LR1121_XF_kiss_modem]
extends = Waveshare_S3_LR1121_XF
build_unflags =
  -DARDUINO_USB_MODE=1
build_flags =
  ${Waveshare_S3_LR1121_XF.build_flags}
  -DARDUINO_USB_MODE=0
build_src_filter = ${Waveshare_S3_LR1121_XF.build_src_filter}
  +<../examples/kiss_modem/>

[env:Waveshare_S3_LR1121_XF_wifi_kiss_modem]
extends = Waveshare_S3_LR1121_XF
build_flags =
  ${Waveshare_S3_LR1121_XF.build_flags}
  -D KISS_WIFI
  -D KISS_WIFI_PORT=27027
  -D WIFI_SSID='"SSID"'
  -D WIFI_PWD='"Password"'
build_src_filter = ${Waveshare_S3_LR1121_XF.build_src_filter}
  +<../examples/kiss_modem/>

[env:Waveshare_S3_LR1121_XF_room_server]
extends = Waveshare_S3_LR1121_XF
build_flags =
  ${Waveshare_S3_LR1121_XF.build_flags}
  -D ADVERT_NAME='"Waveshare S3 LR1121 Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
build_src_filter = ${Waveshare_S3_LR1121_XF.build_src_filter}
  +<../examples/simple_room_server>

[env:Waveshare_S3_LR1121_XF_companion_radio_usb]
extends = Waveshare_S3_LR1121_XF
build_flags =
  ${Waveshare_S3_LR1121_XF.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D ENABLE_USB_INTERFACE
build_src_filter = ${Waveshare_S3_LR1121_XF.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Waveshare_S3_LR1121_XF.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Waveshare_S3_LR1121_XF_companion_radio_ble]
extends = Waveshare_S3_LR1121_XF
build_flags =
  ${Waveshare_S3_LR1121_XF.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter = ${Waveshare_S3_LR1121_XF.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Waveshare_S3_LR1121_XF.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Waveshare_S3_LR1121_XF_companion_radio_wifi]
extends = Waveshare_S3_LR1121_XF
build_flags =
  ${Waveshare_S3_LR1121_XF.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256
  -D WIFI_DEBUG_LOGGING=1
  -D WIFI_SSID='"myssid"'
  -D WIFI_PWD='"mypwd"'
build_src_filter = ${Waveshare_S3_LR1121_XF.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Waveshare_S3_LR1121_XF.lib_deps}
  densaugeo/base64 @ ~1.4.0
